## Numpy Basic and Array

In [1]:
import numpy as np

## Creating array from list

In [2]:
arr_1d = np.array([1,2,3])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array: [1 2 3]
2D array: [[1 2 3]
 [4 5 6]]


## List Vs Array

In [3]:
py_list = [1,2,3]
print("Multiplication of list",py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Multiplication of array",np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(1,100000)]
print("\nList operation time:",time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("Array operation time:",time.time() - start)

Multiplication of list [1, 2, 3, 1, 2, 3]
Multiplication of array [2 4 6]

List operation time: 0.01123499870300293
Array operation time: 0.001565694808959961


### creating array from scratch

In [4]:
zero = np.zeros((3,4))
print("Zeros array:\n",zero)

ones = np.ones((3,4))
print("Ones array:\n",ones)

full = np.full((2,2),5)
print("Full array:\n",full)

random = np.random.random((2,3))
print("Random array:\n",random)

sequnce = np.arange(0,10,2) # non-incluctive
print("Sequnce array:\n",sequnce)

Empty = np.empty(2)
print("Empty array:\n",Empty)

linspace = np.linspace(0,10,num=5)
print("array with values that are spaced linearly:\n",linspace)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array:
 [[5 5]
 [5 5]]
Random array:
 [[0.84105115 0.09159209 0.47175675]
 [0.56434096 0.05819229 0.11475448]]
Sequnce array:
 [0 2 4 6 8]
Empty array:
 [-3.98685300e-010  3.50511161e+278]
array with values that are spaced linearly:
 [ 0.   2.5  5.   7.5 10. ]


### Vector , Matrix and Tensor

In [5]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3] , [4,5,6]])
print("Matrix:",matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor:",tensor)

Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [6]:
arr = np.array([[1,2,3],
               [4,5,6]])

print("Size" , arr.size)
print("Shape" ,arr.shape)
print("Dimension ",arr.ndim)
print("dtype ",arr.dtype)

Size 6
Shape (2, 3)
Dimension  2
dtype  int64


In [7]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped array ",reshaped)

flattened = reshaped.flatten()
print("\nFlattened array ",flattened)

# ravel (returns view , insteead of copy)
raveled = reshaped.ravel()
print("\nraveled array ",raveled)

# Transpose
transpose = reshaped.T
print("\ntranspose array ",transpose)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Array operation and indexing

In [8]:
arr = np.arange(10)

print("Original Array:",arr)
print("Basic Slicing:",arr[3:8])
print("With Step:",arr[1:8:2])
print("Negative indexing:",arr[-3:-1])

Original Array: [0 1 2 3 4 5 6 7 8 9]
Basic Slicing: [3 4 5 6 7]
With Step: [1 3 5 7]
Negative indexing: [7 8]


In [9]:
arr_2d = np.random.randint(10,size=(3,3))

print("Original Array:",arr_2d)
print("Specific element:",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])

Original Array: [[8 6 2]
 [5 1 4]
 [5 5 5]]
Specific element: 4
Entire Row: [5 1 4]
Entire Column: [6 1 5]


### Sorting of Array

In [10]:
unsorted = np.array([1,8,9,6,4,3,2,5,7])

print("Sorted Array:",np.sort(unsorted))

unsorted_2d = np.array([[1,3],[4,2],[6,5]])
print("Sorted Array by Column:",np.sort(unsorted_2d,axis=1)) # axis 1 means left to right
print("Sorted Array by Row:",np.sort(unsorted_2d,axis=0)) # axis 0 means top to bottom

Sorted Array: [1 2 3 4 5 6 7 8 9]
Sorted Array by Column: [[1 3]
 [2 4]
 [5 6]]
Sorted Array by Row: [[1 2]
 [4 3]
 [6 5]]


## Filter and mask

In [11]:
number = np.arange(10)

even = number[number % 2 == 0]
print("Even Numbers:",even)

Even Numbers: [0 2 4 6 8]


In [12]:
mask = number > 5
print("Numbers greater than 5 ",number[mask])

Numbers greater than 5  [6 7 8 9]


## Fancy indexing vs np.where()

In [13]:
indices = [0,2,6]
print(number[indices])

where_result = np.where(number > 5)
print("NP Where ",number[where_result])

condition_array = np.where(number > 5 ,number * 2 , number)   # where (Conditon,True part , False part)
print(condition_array)

[0 2 6]
NP Where  [6 7 8 9]
[ 0  1  2  3  4  5 12 14 16 18]


## Adding and Removing data

In [14]:
arr1 = [1,2,3]
arr2 = [4,5,6]

combine = np.concatenate((arr1,arr2))
print("Combine Array:",combine)

Combine Array: [1 2 3 4 5 6]


In [15]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("Compatibility shape :", a.shape == b.shape)


original = np.array([[1,2],[3,4]])
new_row = np.array([[4,5]])

with_new_row = np.vstack((original,new_row)) # v-stack always add row , row left to right 
print(original)
print()
print(with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col)) # h-stack new column add
print("With new column ",with_new_col)

arr= np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print()
print("Array after deleted :",deleted)

Compatibility shape : True
[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [4 5]]
With new column  [[1 2 7]
 [3 4 8]]

Array after deleted : [1 2 4 5]


## File array

In [16]:
array = np.arange(10)

np.save('array.npy',array)

In [17]:
loded = np.load('array.npy')
print(loded)

[0 1 2 3 4 5 6 7 8 9]
